library(shiny)
library(reshape2)
library(plotly)
library(tidyr)
library(stringr)
library(tidyverse)
library(jsonlite)
library(shinydashboard)
library(shinydashboardPlus)
library(dashboardthemes)
source("./server/utilities.R")
source("./server/server.R")
source("./ui/ui.R")
source("./data/data.R")
source("./data/machine_learning.R")

# Run the application 
shinyApp(ui = ui, server = server)
